# example/claim-eks.yaml
apiVersion: segoja7.example/v1alpha1
kind: XDATABASE
metadata:
  name: xdatabase-example-segoja7
spec:
  id: xdatabase-example-segoja7
  region: us-east-1
  providerConfigName: segoja7
  tags:
    owner: "platform-team"
    environment: "development"
    project: "proyecto"
    managed-by: "crossplane"
  networkId: "xnetwork-example"
  rdsport: 5432
  ipRanges: #todo add SecurityGroupRule
    - cidrIp: "0.0.0.0/0"
      description: "Allow all traffic"
    - cidrIp: "10.0.0.0/16"
      description: "Allow traffic from 10.0.0.0/16"
  rdsDatabase: #TODO implement: encryption with KMS, parameter group
    allocatedStorage: 20
    availabilityZone: us-east-1a
    copyTagsToSnapshot: false
    dbInstanceClass: db.t4g.micro
    dbName: exampledb
    engine: postgres
    engineVersion: "17"
    masterUsername: adminuser
    maxAllocatedStorage: 30    
    multiAZ: false
    storageEncrypted: false
    publiclyAccessible: false
    skipFinalSnapshot: true
    storageType: gp3
  clusterId: "xcluster-example-segoja7" #ID of the cluster where the rds secret will be created
    