apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: master-workload-controller
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: environment
                    operator: NotIn
                    values: [hub]
          
          - git:
              repoURL: https://github.com/segoja7/platform_as_data
              revision: master
              directories:
                - path: xargoapps/gitops-bridge/shared_manifests/*/* 
  
  template:
    metadata:
      name: '{{path.basename}}-{{name}}' 
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/segoja7/platform_as_data
        targetRevision: master
        path: '{{path}}'
      destination:
        name: '{{name}}'
        namespace: '{{path.segments.3}}' 
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
