apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-workload
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: environment
              operator: NotIn
              values: [hub]
  
  template:
    metadata:
      name: 'nginx-global-{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/segoja7/platform_as_data
        targetRevision: master
        path: xargoapps/gitops-bridge/shared_manifests/nginx
        directory:
          recurse: true
      destination:
        name: '{{name}}'
        namespace: workload
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
