# configurations-eks/apis/composition.yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xclusters.segoja7.example
spec:
  compositeTypeRef:
    apiVersion: segoja7.example/v1alpha1
    kind: XCLUSTER
  mode: Pipeline
  pipeline:
  - step: kcl
    functionRef:
      name: crossplane-contrib-function-kcl
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLRun
      spec:
        target: Resources
        source: github.com/segoja7/platform_as_data/xcluster
  - step: auto-ready
    functionRef:
      name: crossplane-contrib-function-auto-ready
