apiVersion: opentofu.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  # This is the default ProviderConfig that Workspaces will use
  name: default2
spec:
  configuration: |
    terraform {
      backend "s3" {
        bucket                   = "9102025-my-tf-state-bucket"
        key                      = "crossplane/tofu/my_key"
        region                   = "us-east-1"
        shared_credentials_files = ["aws-creds.ini"]
        profile                  = "default"
      }
    }

    provider "aws" {
      region                   = "us-east-1"
      shared_credentials_files = ["${path.module}/aws-creds.ini"]
      profile                  = "default"
    }
  credentials:
    - filename: aws-creds.ini
      secretRef:
        key: creds
        name: aws-secrets
        namespace: crossplane-system
      source: Secret
