apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xdatabases.segoja7.example
spec:
  compositeTypeRef:
    apiVersion: segoja7.example/v1alpha1
    kind: XDATABASE
  mode: Pipeline
  pipeline:
  - step: kcl
    functionRef:
      name: crossplane-contrib-function-kcl
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLRun
      spec:
        target: Resources
        source: github.com/segoja7/platform_as_data/xdatabase
  - step: auto-ready
    functionRef:
      name: crossplane-contrib-function-auto-ready
